# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Network Automation
tagline:          'Brownfield (mostly)'
description:      'Observations in network automation<br /> <a href="https://twitter.com/termlen0" target="_blank">@termlen0</a>'
url:              http://termlen0.github.io
baseurl:          /

author:
  name:           'Ajay Chenampara'
  url:            https://twitter.com/termlen0
  linkedin:       https://linkedin.com/u/achenampara

paginate:         5

excerpt_separator: "<!--more-->"

gems:
  - jekyll-paginate
  - redcarpet
  - kramdown
  - jekyll-gist
  - pygments.rb

plugins:
  - jekyll-paginate
#Archive
pages_list:
  Archive: '/archive'

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/termlen0

theme: jekyll-theme-minimal
