# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            TEST
tagline:          'A Jekyll themed blog'
description:      'A log of my observations in the network automation domain. <a href="https://twitter.com/termlen0" target="_blank">@termlen0</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ajay Chenampara'
  url:            https://twitter.com/termlen0

paginate:         5
gems: 
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/termlen0
